Repository vortexntnu/vortex-cv, pull requests merged in 2022-01, with the labels that each got.

#14 Bugfix/removal of deprecated stuff
  object_detection/launch/object_detection_node.launch
  object_detection/scripts/object_detection_node.py
  object_detection/scripts/old_code.py
  object_detection/scripts/pointcloud_mapping.py
  object_detection/scripts/position_estimator.py
Labels: bug, enhancement

#16 made messages Point2 and PointArray
  cv_msgs/CMakeLists.txt
  cv_msgs/msg/Point2.msg
  cv_msgs/msg/PointArray.msg
Labels: enhancement

#21 created pipeline, needs testing
  cv_msgs/msg/PointArray.msg
  object_detection/launch/pointcloud_downsampler.launch
  object_detection/scripts/object_detection_node.py
  object_detection/scripts/pointcloud_mapping.py
Labels: documentation, enhancement

#22 Enhancement/point array publish
  feature_detection/object_cfgs/gate_1.yaml
  feature_detection/object_cfgs/gate_2.yaml
  feature_detection/object_cfgs/path_detection.yaml
  feature_detection/object_cfgs/pole_cfg.yaml
  feature_detection/scripts/feature_detection_node.py
  feature_detection/scripts/read_yaml_config.py
Labels: enhancement

#31 Restructure/split into packages
  cv_utils/CMakeLists.txt
  cv_utils/launch/rosbag_to_jpeg.launch
  cv_utils/package.xml
  object_detection/scripts/pointcloud_mapping.py
  pointcloud_processing/CMakeLists.txt
  pointcloud_processing/README.md
  pointcloud_processing/launch/pointcloud_downsampler.launch
  pointcloud_processing/launch/pointcloud_processing_node.launch
  pointcloud_processing/package.xml
  pointcloud_processing/scripts/coord_pos.py
  pointcloud_processing/scripts/old_code.py
  pointcloud_processing/scripts/pointcloud_mapping.py
  pointcloud_processing/scripts/pointcloud_processing_node.py
  pointcloud_processing/scripts/position_estimator.py
  vision_launch/CMakeLists.txt
  vision_launch/launch/vision_launch.launch
  vision_launch/package.xml
Labels: refactor

#35 Documentation/repo readme
  README.md
  docs/Vortex-CV_dataflow.jpg
Labels: documentation
